### ISSUE TITLE
Cheogram MUC connect sometimes fails silently (maybe no retry logic?)

### ISSUE THREAD

**Issue by ossguy** [singpolyma/cheogram#64]
I had two numbers joined to two different MUCs hosted on the same server as Cheogram and found that when Prosody was restarted on that server, the numbers were no longer joined to the MUCs.  This happened shortly after 2017-03-22T14:22:55Z (when the last message was received by these numbers) and probably before 2017-03-22T14:24:32Z (when I connected to one of the MUCs via a different JID, after the Prosody restart) - no messages were received on either number after 2017-03-22T14:22:55Z.

I suspect that Cheogram tried to reconnect to the MUCs after it was restarted, but perhaps Prosody wasn't done starting yet, and so the MUC connection failed, and maybe Cheogram didn't retry.  That's just a guess, though.

**Comment by singpolyma** [comment]
The "You have left" message was sent, but probably prosody shutdown had already happened by then and so the message was never delivered.  Since cheogram gets told you've been booted from the room by prosody, this is the right behaviour so far as it is concerned.  May want to revisit the non-delivery in the future if we co-host many MUCs with cheogram, but in general this should not affect any other cases.  Closing for now.
